### ISSUE TITLE
 ERROR: failed to solve: process "/bin/sh -c chmod +x /entrypoint.sh" did not complete successfully: exit code: 1

### ISSUE THREAD

**Issue by Badr-Tarek** [SonarSource/sonarqube-scan-action#104]
0.165 chmod: /entrypoint.sh: Operation not permitted

**Comment by richard-green** [comment]
Also getting this:

> #8 0.184 chmod: /entrypoint.sh: Operation not permitted
  #8 ERROR: process "/bin/sh -c chmod +x /entrypoint.sh" did not complete successfully: exit code: 1

**Comment by wooseung-sim** [comment]
Same here

**Comment by cedric-appdirect** [comment]
I am also seeing this since this morning. It was working fine 16 hours ago. It is a bit concerning as there was no new release of this action.

**Comment by mcarrillowz** [comment]
Same, the [Docker image](https://hub.docker.com/r/sonarsource/sonar-scanner-cli/tags) was updated 26 minutes ago
<img width="1214" alt="image" src="https://github.com/SonarSource/sonarqube-scan-action/assets/50845831/17d5e507-1823-4a62-9a28-b33a57415f7e">

**Comment by dchekirda** [comment]
See this problem as well. Worked about few hours before without issues.

**Comment by paulomcnally** [comment]
```
/usr/bin/docker build -t a6b84c:b5f9e2265622469fa398122ab4656888 -f "/home/runner/work/_actions/sonarsource/sonarqube-scan-action/master/Dockerfile" "/home/runner/work/_actions/sonarsource/sonarqube-scan-action/master"
  #0 building with "default" instance using docker driver
  
  #1 [internal] load .dockerignore
  #1 transferring context: 2B done
  #1 DONE 0.0s
  
  #2 [internal] load build definition from Dockerfile
  #2 transferring dockerfile: 713B done
  #2 DONE 0.0s
  
  #3 [internal] load metadata for docker.io/sonarsource/sonar-scanner-cli:5.0.1
  #3 ...
  
  #4 [auth] sonarsource/sonar-scanner-cli:pull token for registry-1.docker.io
  #4 DONE 0.0s
  
  #3 [internal] load metadata for docker.io/sonarsource/sonar-scanner-cli:5.0.1
  #3 DONE 0.7s
  
  #5 [internal] load build context
  #5 transferring context: 1.50kB done
  #5 DONE 0.0s
  
  #6 [1/5] FROM docker.io/sonarsource/sonar-scanner-cli:5.0.1@sha256:c137f8c67272971c001aad747dce830d81d62dce25acd0e4b8ae7290b225657c
  #6 resolve docker.io/sonarsource/sonar-scanner-cli:5.0.1@sha256:c137f8c67272971c001aad747dce830d81d62dce25acd0e4b8ae7290b225657c done
  #6 extracting sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1 done
  #6 sha256:d365f01690bdede439d1a63dfae47b45094a5cb56793a9364b013d3015011dc8 4.82kB / 4.82kB done
  #6 sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1 32B / 32B 0.1s done
  #6 sha256:77aac2b8cbb6a7dbf8c9fa2e73a04c9d77e9517f5e9eb661997a1000a042c4cc 0B / 99.47MB 0.1s
  #6 sha256:6180196e68a7518ea1de1b0734c3b28e4e0d17e623263e13f79978c48c440f09 0B / 736B 0.1s
  #6 sha256:c137f8c67272971c001aad747dce830d81d62dce25acd0e4b8ae7290b225657c 1.36kB / 1.36kB done
  #6 sha256:77aac2b8cbb6a7dbf8c9fa2e73a04c9d77e9517f5e9eb661997a1000a042c4cc 9.44MB / 99.47MB 0.3s
  #6 sha256:6180196e68a7518ea1de1b0734c3b28e4e0d17e623263e13f79978c48c440f09 736B / 736B 0.2s done
  #6 sha256:77aac2b8cbb6a7dbf8c9fa2e73a04c9d77e9517f5e9eb661997a1000a042c4cc 19.92MB / 99.47MB 0.4s
  #6 sha256:77aac2b8cbb6a7dbf8c9fa2e73a04c9d77e9517f5e9eb661997a1000a042c4cc 27.26MB / 99.47MB 0.5s
  #6 sha256:77aac2b8cbb6a7dbf8c9fa2e73a04c9d77e9517f5e9eb661997a1000a042c4cc 33.55MB / 99.47MB 0.6s
  #6 sha256:77aac2b8cbb6a7dbf8c9fa2e73a04c9d77e9517f5e9eb661997a1000a042c4cc 49.28MB / 99.47MB 0.8s
  #6 sha256:77aac2b8cbb6a7dbf8c9fa2e73a04c9d77e9517f5e9eb661997a1000a042c4cc 59.77MB / 99.47MB 0.9s
  #6 sha256:77aac2b8cbb6a7dbf8c9fa2e73a04c9d77e9517f5e9eb661997a1000a042c4cc 66.06MB / 99.47MB 1.0s
  #6 sha256:77aac2b8cbb6a7dbf8c9fa2e73a04c9d77e9517f5e9eb661997a1000a042c4cc 78.64MB / 99.47MB 1.1s
  #6 sha256:77aac2b8cbb6a7dbf8c9fa2e73a04c9d77e9517f5e9eb661997a1000a042c4cc 99.47MB / 99.47MB 1.3s
  #6 sha256:77aac2b8cbb6a7dbf8c9fa2e73a04c9d77e9517f5e9eb661997a1000a042c4cc 99.47MB / 99.47MB 1.5s done
  #6 extracting sha256:77aac2b8cbb6a7dbf8c9fa2e73a04c9d77e9517f5e9eb661997a1000a042c4cc
  #6 extracting sha256:77aac2b8cbb6a7dbf8c9fa2e73a04c9d77e9517f5e9eb661997a1000a042c4cc 2.6s done
  #6 extracting sha256:6180196e68a7518ea1de1b0734c3b28e4e0d17e623263e13f79978c48c440f09
  #6 extracting sha256:6180196e68a7518ea1de1b0734c3b28e4e0d17e623263e13f79978c48c440f09 done
  #6 DONE 6.7s
  
  ------
  Dockerfile:14
  --------------------
    12 |     
    13 |     COPY entrypoint.sh /entrypoint.sh
    14 | >>> RUN chmod +x /entrypoint.sh
    15 |     COPY cleanup.sh /cleanup.sh
    16 |     RUN chmod +x /cleanup.sh
  --------------------
  ERROR: failed to solve: process "/bin/sh -c chmod +x /entrypoint.sh" did not complete successfully: exit code: 1
  Warning: Docker build failed with exit code 1, back off 9.551 seconds before retry.
  /usr/bin/docker build -t a6b84c:b5f9e2265622469fa398122ab4656888 -f "/home/runner/work/_actions/sonarsource/sonarqube-scan-action/master/Dockerfile" "/home/runner/work/_actions/sonarsource/sonarqube-scan-action/master"
  #0 building with "default" instance using docker driver
  
  #1 [internal] load .dockerignore
  #1 transferring context: 2B done
  #1 DONE 0.0s
  
  #2 [internal] load build definition from Dockerfile
  #2 transferring dockerfile: 713B done
  #2 DONE 0.0s
  
  #3 [internal] load metadata for docker.io/sonarsource/sonar-scanner-cli:5.0.1
  #3 DONE 0.2s
  
  #4 [1/5] FROM docker.io/sonarsource/sonar-scanner-cli:5.0.1@sha256:c137f8c67272971c001aad747dce830d81d62dce25acd0e4b8ae7290b225657c
  #4 DONE 0.0s
  
  #5 [internal] load build context
  #5 transferring context: 65B done
  #5 DONE 0.0s
  
  #6 [2/5] COPY entrypoint.sh /entrypoint.sh
  #6 CACHED
  
  #7 [3/5] RUN chmod +x /entrypoint.sh
  #7 0.174 chmod: /entrypoint.sh: Operation not permitted
  #7 ERROR: process "/bin/sh -c chmod +x /entrypoint.sh" did not complete successfully: exit code: 1
  ------
   > [3/5] RUN chmod +x /entrypoint.sh:
  0.174 chmod: /entrypoint.sh: Operation not permitted
  ------
  Dockerfile:14
  --------------------
    12 |     
    13 |     COPY entrypoint.sh /entrypoint.sh
    14 | >>> RUN chmod +x /entrypoint.sh
    15 |     COPY cleanup.sh /cleanup.sh
    16 |     RUN chmod +x /cleanup.sh
  --------------------
  ERROR: failed to solve: process "/bin/sh -c chmod +x /entrypoint.sh" did not complete successfully: exit code: 1
Error: Docker build failed with exit code 1
```

**Comment by cedric-appdirect** [comment]
As pointed above a new image has been pushed and override the 9 months old 5.0.1 release with a new release with the same docker tag. This is now pulled by this github action. I think the fix should be in the sonar-scanner-cli-docker. It should not ever overwrite a release.

**Comment by kevin-kraus** [comment]
Same also happening for https://github.com/SonarSource/sonarcloud-github-action.

Issue in Parent Image Repo: https://github.com/SonarSource/sonar-scanner-cli-docker/issues/224

**Comment by damanrique** [comment]
same error with docker image

**Comment by wwsean08** [comment]
A temp fix is to point at commit sha `465a122c48499009db491f0847ecee9cf9f20b50` which is in my fork that I generated to unblock the reusable workflows at my job, this forces it to use the previously working container

**Comment by ivan-poznyak-mint** [comment]
same issue

**Comment by drilonibrahimi** [comment]
> to workaround I fixed my action in this version sonarsource/sonarqube-scan-action@v1.2.0 this version user cli-4.8

Can confirm this worked on my use case, thx @guerlielton-nunes

**Comment by damanrique** [comment]
> v1.2.0

it works as a workaround. thanks

**Comment by rathpc** [comment]
also have this problem but down-pinning to 1.2.0 is not an option. anyone from sonar willing to chime in on this issue?

@claire-villard-sonarsource @matteo-mara-sonarsource

**Comment by dsayling** [comment]
Interesting that pinning the image in the _other_ action is what's being done...

https://github.com/SonarSource/sonarcloud-github-action/pull/67

**Comment by ronaldofysight** [comment]
Same issue.

```
  #8 [3/5] RUN chmod +x /entrypoint.sh
  #8 0.178 chmod: /entrypoint.sh: Operation not permitted
  #8 ERROR: process "/bin/sh -c chmod +x /entrypoint.sh" did not complete successfully: exit code: 1
```

**Comment by Ifletcher668** [comment]
Same issue here

**Comment by mattriordan1uphealth** [comment]
> A temp fix is to point at commit sha `465a122c48499009db491f0847ecee9cf9f20b50` which is in my fork that I generated to unblock the reusable workflows at my job, this forces it to use the previously working container

This sha worked for us while v1.2.0 did not.

**Comment by arrmansa** [comment]
I have the same issue with the rick and morty hash 
c137f8c67272971c001aad747dce830d81d62dce25acd0e4b8ae7290b225657c
the previous one worked correctly
494ecc3b5b1ee1625bd377b3905c4284e4f0cc155cff397805a244dee1c7d575

**Comment by psadi** [comment]
Facing the same error

```sh
#9 [4/6] RUN chmod +x /entrypoint.sh
  #9 0.176 chmod: /entrypoint.sh: Operation not permitted
  #9 ERROR: process "/bin/sh -c chmod +x /entrypoint.sh" did not complete successfully: exit code: 1
  ------
   > [4/6] RUN chmod +x /entrypoint.sh:
  0.176 chmod: /entrypoint.sh: Operation not permitted
  ------
  Dockerfile:24
  --------------------
    22 |     # Prepare entrypoint
    23 |     COPY entrypoint.sh /entrypoint.sh
    24 | >>> RUN chmod +x /entrypoint.sh
    25 |     COPY cleanup.sh /cleanup.sh
    26 |     RUN chmod +x /cleanup.sh
  --------------------
  ERROR: failed to solve: process "/bin/sh -c chmod +x /entrypoint.sh" did not complete successfully: exit code: 1
  Warning: Docker build failed with exit code 1, back off 8.997 seconds before retry.
  /usr/bin/docker build -t f3e1f2:00e283dde[55](https://github.com/psadi/bbcli/actions/runs/8709992075/job/23890878538#step:2:55)84fceab9582a840bb65be -f "/home/runner/work/_actions/sonarsource/sonarcloud-github-action/master/Dockerfile" "/home/runner/work/_actions/sonarsource/sonarcloud-github-action/master"
```


any suggestions ?

**Comment by sveinse** [comment]
Same here.  2 hours ago it worked and then it stopped. Something changed either with this action or in the github environment very recently.

**Comment by jupitercl** [comment]
Same here

**Comment by mviegasdeb** [comment]
SAME BRO

**Comment by andrevandal** [comment]
same here

**Comment by fabiocruzcoelho** [comment]
same here

**Comment by ademolaarigbabuwo-8451** [comment]
same here

**Comment by elmijo** [comment]
same here

**Comment by lsadam0** [comment]
I just want to be sure, is the issue also happening to everyone else here?

**Comment by kumar08401** [comment]
Hi Team,

having issue with this plugin, geeting below error

Dockerfile:24
  --------------------
    22 |     # Prepare entrypoint
    23 |     COPY entrypoint.sh /entrypoint.sh
    24 | >>> RUN chmod +x /entrypoint.sh
    25 |     COPY cleanup.sh /cleanup.sh
    26 |     RUN chmod +x /cleanup.sh

**Comment by andrevandal** [comment]
guys, [G Ann Campbell](https://community.sonarsource.com/u/ganncamp) said:

> There is currently an outage related to the SonarScanner CLI Docker image that affects the GitHub actions for both SonarQube and SonarCloud.
> 
> We are aware of the problem and are working to solve it.
> 
> In the meantime, you can work around this
> 
> For SonarQube
> Pin to version 2.0 of the scan action to use the older (working) version of the scan action
> 
> We apologize for the inconvenience.
> 
>  
> Ann & the Sonar team

https://community.sonarsource.com/t/outage-sonarscanner-cli-docker-sonarqube-sonarcloud-github-actions/113548

**Comment by LuccasSartori** [comment]
> to workaround I fixed my action in this version sonarsource/sonarqube-scan-action@v1.2.0 this version user cli-4.8

This worked for me, tks.

**Comment by elmijo** [comment]
> I just want to be sure, is the issue also happening to everyone else here?

yep, it's the same issue:
```bash
  #7 [3/5] RUN chmod +x /entrypoint.sh
  #7 0.178 chmod: /entrypoint.sh: Operation not permitted
  #7 ERROR: process "/bin/sh -c chmod +x /entrypoint.sh" did not complete successfully: exit code: 1
  ------
   > [3/5] RUN chmod +x /entrypoint.sh:
  0.178 chmod: /entrypoint.sh: Operation not permitted
  ------
  Dockerfile:14
  --------------------
    12 |     
    13 |     COPY entrypoint.sh /entrypoint.sh
    14 | >>> RUN chmod +x /entrypoint.sh
    15 |     COPY cleanup.sh /cleanup.sh
    16 |     RUN chmod +x /cleanup.sh
  --------------------
  ERROR: failed to solve: process "/bin/sh -c chmod +x /entrypoint.sh" did not complete successfully: exit code: 1
```

**Comment by dsayling** [comment]
> guys, [G Ann Campbell](https://community.sonarsource.com/u/ganncamp) said:
> 
> > There is currently an outage related to the SonarScanner CLI Docker image that affects the GitHub actions for both SonarQube and SonarCloud.
> > We are aware of the problem and are working to solve it.
> > In the meantime, you can work around this
> > For SonarQube
> > Pin to version 2.0 of the scan action to use the older (working) version of the scan action
> > We apologize for the inconvenience.
> > Ann & the Sonar team
> 
> https://community.sonarsource.com/t/outage-sonarscanner-cli-docker-sonarqube-sonarcloud-github-actions/113548

an "outage"?? 

This is not an _outage_, this was a bad release that overwrote an existing docker tag that impacted downstream dependencies.

**Comment by vyas-n** [comment]
@dsayling For GitHub Actions, this is the equivalent of an outage.

> this was a bad release that overwrote an existing docker tag that impacted downstream dependencies.

Similar to if we're doing an HTTP call to a web server and that web server is down. Our HTTP call is not an outage, it's just affected by being a downstream dependency of a web server.

**Comment by svaranasi-corporate** [comment]
> guys, [G Ann Campbell](https://community.sonarsource.com/u/ganncamp) said:
> 
> > There is currently an outage related to the SonarScanner CLI Docker image that affects the GitHub actions for both SonarQube and SonarCloud.
> > We are aware of the problem and are working to solve it.
> > In the meantime, you can work around this
> > For SonarQube
> > Pin to version 2.0 of the scan action to use the older (working) version of the scan action
> > We apologize for the inconvenience.
> > Ann & the Sonar team
> 
> https://community.sonarsource.com/t/outage-sonarscanner-cli-docker-sonarqube-sonarcloud-github-actions/113548

Doesn't work for me. I get the same error with v2.0.0.

**Comment by wooseung-sim** [comment]
> > guys, [G Ann Campbell](https://community.sonarsource.com/u/ganncamp) said:
> > > There is currently an outage related to the SonarScanner CLI Docker image that affects the GitHub actions for both SonarQube and SonarCloud.
> > > We are aware of the problem and are working to solve it.
> > > In the meantime, you can work around this
> > > For SonarQube
> > > Pin to version 2.0 of the scan action to use the older (working) version of the scan action
> > > We apologize for the inconvenience.
> > > Ann & the Sonar team
> > 
> > 
> > https://community.sonarsource.com/t/outage-sonarscanner-cli-docker-sonarqube-sonarcloud-github-actions/113548
> 
> Doesn't work for me. I get the same error with v2.0 as well as v2.0.0.. yes they have 2 tags!

Seems like wrong instructions. Per commit history of the action, working version should be v1.2.0.

**Comment by dsayling** [comment]
Confirmed - issue is resolved using `sonarqube-scan-action@master`

**Comment by matheusalxds** [comment]
> Confirmed - issue is resolved (at least using `sonarqube-scan-action@master`) Other versions should probably be just fine again as well

Yeah! It's everything working fine! :D
