### ISSUE TITLE
The sonar scanner is unable to detect the coverage.lcov.info report path.

### ISSUE THREAD

**Issue by pratimk1411** [SonarSource/sonarqube-scan-action#106]
Hi @sonarsource/sonarqube-team
The sonar scanner is unable to detect the coverage.lcov.info report path.
Please update sonar.javascript.lcov.reportPaths file path for sonar-project.properties files.
Need to run the scan for the JavaScript and typescript!!
It doesn't show the code coverage without these path being referred. 
Please fix this asap.

**Comment by henryju** [comment]
We are closing the GitHub issues section on this repo. If you need more help, please open a thread on our [community forum](https://community.sonarsource.com/).
