### ISSUE TITLE
Unable to scan project that uses Typescript 5.4

### ISSUE THREAD

**Issue by robinvdvleuten** [SonarSource/sonarqube-scan-action#121]
I'm currently working on a project using Typescript 5.4. Its configured to use `preserve` for the `module` configuration option (see https://www.typescriptlang.org/tsconfig/#preserve). The logs of the scan action shows the following error, and thus typescript source files aren't scanned anymore. 

```
ERROR: Error: Argument for '--module' option must be: 'none', 'commonjs', 'amd', 'system', 'umd', 'es6', 'es2015', 'es2020', 'es2022', 'esnext', 'node16', 'nodenext'.  /github/workspace/tsconfig.json:4
ERROR:     at createProgramOptions (/github/workspace/.scannerwork/.sonartmp/eslint-bridge-bundle/package/lib/services/program/program.js:106:15)
```

I noticed that SonarJS does support Typescript 5.4 (https://github.com/SonarSource/SonarJS/pull/4613), so my question is if this can be updated in the action as well?

**Comment by csaba-feher-sonarsource** [comment]
Hi @robinvdvleuten, What SonarQube version are you using?

**Comment by robinvdvleuten** [comment]
I am using the latest version of the scan action, is there any way to see this?

**Comment by csaba-feher-sonarsource** [comment]
Hi @robinvdvleuten,

You can find the version of SonarQube can be found under :
https://docs.sonarsource.com/sonarqube/9.6/instance-administration/license-administration/
SonarQube version - Found under System Info at Administration > System

We are happy to continue this discussion, but we would like to retire the issues page and have all the community support going through our community forum: https://community.sonarsource.com/. If you need further assistance, would you mind reopening the question there?


Thanks
Csaba

**Comment by csaba-feher-sonarsource** [comment]
I am closing this thread as we are retiring the issues page all future support cases will be handled for sonar-scan action on https://community.sonarsource.com/
