### ISSUE TITLE
Required SONAR_TOKEN - should it be optional?

### ISSUE THREAD

**Issue by LDaneliukas** [SonarSource/sonarqube-scan-action#15]
Currrently the `SONAR_TOKEN` is a required input for the action to operate, however, SonarQube allows analysis without [authentication](https://docs.sonarqube.org/latest/instance-administration/security) if the administrator chooses so.

The action could support this by having the `SONAR_TOKEN` as an optional input that controls whether we attempt to authenticate or not. Now, even if your SonarQube instance is configured not to require user authentication, the action will still fail, as you are required to configure a token which is then passed on to SonarQube and gets validated.

**Comment by asangas** [comment]
+1. We ran into the same issue as our Sonar instance does not require authentication. 

The action should not be opinionated about turning on auth in the SonarQuebe instance.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi there,

yes this makes sense. i have created https://jira.sonarsource.com/browse/SONAR-16068 to track this

**Comment by tobias-trabelsi-sonarsource** [comment]
fixed with #25
