### ISSUE TITLE
Cannot reference GitHub Runner's 'localhost' 

### ISSUE THREAD

**Issue by tylerzisk** [SonarSource/sonarqube-scan-action#16]
My company uses a bastion to connect to our self-hosted SonarQube instance, and this bastion sets up against `localhost:8080` for the GitHub Runner. However, I cannot reference the external `localhost` of the Docker container that this action runs from. I tried using the `host.docker.internal` but you have to add a `--add-host` flag when starting the container in order to achieve this. Really like this action, but I currently would have to just get the Docker image myself and add these run parameters (which we'd rather not do). 

An easy fix for this would to build the Docker image and add the `--net="host"` parameter, which will have the container reference `localhost` as the host machine's value, not the container itself.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @tylerzisk,

options should help you here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontainer

if you are facing other issues, feel free to create a thread in our [community forum](https://community.sonarsource.com/)
