### ISSUE TITLE
Issues with ipv6

### ISSUE THREAD

**Issue by jevon71-work** [SonarSource/sonarqube-scan-action#21]
We are seeing issues with this Action, when it is run on Self-Hosted Runner in AWS and needs to access an enterprise SonarQube server.  Can you advise if there is a way to force the container to only use ipv4 and if so, can you ensure this is properly defined in the documentation?

Thanks,

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @jevon71-work ,

i think you need to look at the docker daemon configuration of your self hosted runner. the container engine is responsible for the network stack and not the github action.
if you are still facing issues feel free to create a new thread in our [community forum](https://community.sonarsource.com/)
