### ISSUE TITLE
Fails to connect to Sonarqube server signed by corporate PKI 

### ISSUE THREAD

**Issue by nv35** [SonarSource/sonarqube-scan-action#26]
Hi,

We've an internal sonarqube server, that is using a certificate signed by corporate PKI.
Action doesn't want to connect to it.

> org.sonarsource.scanner.api.internal.ScannerException: Unable to execute SonarScanner analysis
> Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

I had to fork the action repo and add following lines to the Dockerfile
```lang=Dockerfile
# Add certificate in java keystore
COPY sonarqube.corp.net.pem .
RUN keytool -keystore /etc/ssl/certs/java/cacerts -storepass changeit -noprompt -trustcacerts -importcert -alias sonarqube -file sonarqube.corp.net.pem
```

There should be an option to deal with the issue (use cert store of the host, accept as arg the hash of the certificate to trust...). It may be possible to solve that with java arg, but if it's the case it may be great to add it in the Readme.

Thanks

**Comment by bspach** [comment]
+1 We are also having to fork this repo due to this limitation

**Comment by wouter-admiraal-sonarsource** [comment]
Hi.

I'm not sure how we could achieve this (and happy to read any suggestions). Because AFAIK, you need to mount these certificates inside the running Docker container, and this is not something that you can achieve using GitHub Actions (i.e., you cannot mount custom folders). For this to work, you would need to put these certificates inside your working directory alongside your source code, which isn't ideal and not something we would do.

So unless I'm missing something, I will close this request. Feel free to re-open if there's a clean solution to this that I'm unaware of.

**Comment by willemvantonder0** [comment]
@bspach & @nv35 
Would it be possible to elaborate a bit on this please?
How does your GitHub Action Workflow now look like since you had to fork from this repo, and then still use the same "sonarsource/sonarqube-scan-action@master" step?
Or since the fork, does the GH workflow look completely different?
We are also at a private organization which certificate was signed by a corporate PKI. Im getting the exact same issue.

**Comment by nv35** [comment]
> @bspach & @nv35 Would it be possible to elaborate a bit on this please? How does your GitHub Action Workflow now look like since you had to fork from this repo, and then still use the same "sonarsource/sonarqube-scan-action@master" step? Or since the fork, does the GH workflow look completely different? We are also at a private organization which certificate was signed by a corporate PKI. Im getting the exact same issue.

I had to fork the repo, apply the change listed in the first comment to the Dockerfile, add the needed cert file to the repo, and then use this fork in my pipelines (instead of using "sonarsource/sonarqube-scan-action@master", use "nv35/sonarqube-scan-action@master").

**Comment by nv35** [comment]
> Hi.
> 
> I'm not sure how we could achieve this (and happy to read any suggestions). Because AFAIK, you need to mount these certificates inside the running Docker container, and this is not something that you can achieve using GitHub Actions (i.e., you cannot mount custom folders). For this to work, you would need to put these certificates inside your working directory alongside your source code, which isn't ideal and not something we would do.
> 
> So unless I'm missing something, I will close this request. Feel free to re-open if there's a clean solution to this that I'm unaware of.

Hi, perhaps another solution would be to give the certificate as text input (variable) to the action, instead of file? Then the keytool command would be called in entrypoint script, rather than at the docker build. I've not tested if keytool can run as non root.

**Comment by wouter-admiraal-sonarsource** [comment]
Hi @nv35 ,

That's a good idea. I've opened [this ticket](https://sonarsource.atlassian.net/browse/SQSCANGHA-6) to keep track of this. I cannot make any promises about when we'll deliver it, but we'll try and make it happen :-).

As we now have this in our backlog, I'll keep this issue's status closed.

**Comment by willemvantonder0** [comment]
> > @bspach & @nv35 Would it be possible to elaborate a bit on this please? How does your GitHub Action Workflow now look like since you had to fork from this repo, and then still use the same "sonarsource/sonarqube-scan-action@master" step? Or since the fork, does the GH workflow look completely different? We are also at a private organization which certificate was signed by a corporate PKI. Im getting the exact same issue.
> 
> I had to fork the repo, apply the change listed in the first comment to the Dockerfile, add the needed cert file to the repo, and then use this fork in my pipelines (instead of using "sonarsource/sonarqube-scan-action@master", use "nv35/sonarqube-scan-action@master").

Thank you @nv35 . I used your approach and it works well !!!
Something I have found in addition is that one can also go and either run the SonarScanner Linux Agent or Docker Container (from DockerHub), as per the following link: https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/
Again, thanks for your guidance.
