### ISSUE TITLE
Scan failure broke runner with "stderr maxBuffer length exceeded"

### ISSUE THREAD

**Issue by nv35** [SonarSource/sonarqube-scan-action#27]
## Problem
When the scan return an error (ie. `QUALITY GATE STATUS: FAILED `), the further jobs running on the same runner will fails. The runner is "intoxicated", and is the unusable at all (even for pipelines not involving sonarqube).

Log from a job, running after a `SonarSource/sonarqube-scan-action@master` scan failure:
```
##[group]Run actions/checkout@v2
...
Cleaning the repository
  /usr/bin/git clean -ffdx
  warning: failed to remove .scannerwork/.sonar_lock: Permission denied
  warning: failed to remove .scannerwork/ucfg2/js/static_js_jquery_easing_1_3_js_145_15_FE_100_x_t_b_c_d_s.ucfg: Permission denied
  warning: failed to remove .scannerwork/ucfg2/js/static_js_main_js_153_21_FE_25_0.ucfg: Permission denied
  warning: failed to remove .scannerwork/ucfg2/js/static_js_jquery_style_switcher_js_177_21_FE_116_ass.ucfg: Permission denied
  warning: failed to remove .scannerwork/ucfg2/js/static_js_main_js_207_41_FE_34_k.ucfg: Permission denied
  warning: failed to remove .scannerwork/ucfg2/js/static_js_jquery_style_switcher_js_107_9_FE_110_0.ucfg: Permission denied
...
##[endgroup]
##[warning]Unable to clean or reset the repository. The repository will be recreated instead.
Deleting the contents of '/xx/actions-runner/_work/xx/xx'
##[error]stderr maxBuffer length exceeded
```

![image](https://user-images.githubusercontent.com/76777923/166678936-35f35f26-5095-45f6-9d49-e76359a1844b.png)

Pipeline definition:
```
  sonarqube:
    name: SonarQube tests
    runs-on: [ ec2 ]
    steps:
      - uses: actions/checkout@v2
      - name: SonarQube scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarqube.corp.net
```
On an self-hosted github actions runner, with a self-hosted sonarqube server.

## Cause
Scan made by this action is done by execution a Docker container. When the scan return an error (ie. `QUALITY GATE STATUS: FAILED `), the folder `.scannerwork` created by the scanner is not deleted, and its filesystem owner is keep to the creator of the folder - the user that runs the scan inside the docker container. The temporary permissions are never corrected, because the [commands that should do it](https://github.com/SonarSource/sonarqube-scan-action/blob/master/entrypoint.sh#L30) are after the location where the script exit.
Github tries to cleanup the workspace folder at each job start. Problem occurs because `.scannerwork` is owned by a different linux user than the one executing the cleanup, and permission is denied then. No jobs can be executed while folder is not manually deleted.
It occurs when [id of the user](https://github.com/SonarSource/sonar-scanner-cli-docker/blob/master/4/Dockerfile#L5) in the docker container is different than the github runner process id.
Temporary solution is to delete the folder manually with a root user shell.

**Comment by wouter-admiraal-sonarsource** [comment]
Hi @nv35 .

Thanks for the detailed report. Indeed, this is because the clean-up isn't run when explicitly waiting on the Quality Gate status. [This PR](https://github.com/SonarSource/sonarqube-scan-action/pull/33) should fix it.
