### ISSUE TITLE
Action leaves .scannerwork owned by root in case of cancel during the step

### ISSUE THREAD

**Issue by bsvobodny** [SonarSource/sonarqube-scan-action#31]
Hi,

I looked at the issue #22 and the pull request #25 which is supposed to fix this issue.
It seems to work fine for most of the time.
But because the `chown` used to bring back the folder `.scannerwork` from root to user is done at the end, it still let the possibility to leave the runner with `.scannerwork` owned by root in case of cancel or any other issue during the process.

Could you find a solution to that problem ? 
Is using Post action treatment a possibility ?

**Comment by githilman** [comment]
Having the same issue here. In my case, `.scannerwork` was still owned by root when my scan failed the quality gate I set. When it succeeds it should be no problem.

**Comment by bsvobodny** [comment]
OH, your issue is worst than mine, it could happen often !!!
This issue should have a higher priority  !!!!

**Comment by jay-walters** [comment]
Having the same issue as @bsvobodny described above when cancelled.

I completely agree that this issue should have a higher priority.

**Comment by bsvobodny** [comment]
This issue seems to be related to this one #27 which has an in progress Pull Request  🤞

**Comment by bsvobodny** [comment]
In fact the Pull Request #27 doesn't seem to fix the issue, I made my own Pull Request #33, do not hesitate to review it and to give me your feedback 😉

**Comment by bsvobodny** [comment]
@wouter-admiraal-sonarsource @tobias-trabelsi-sonarsource @julien-carsique-sonarsource Could you please have a look to the Pull request that should fix this issue #33 

Thanks

**Comment by jay-walters** [comment]
@wouter-admiraal-sonarsource @tobias-trabelsi-sonarsource @julien-carsique-sonarsource - I am with @bsvobodny and could really use the fix addressed by this code change

**Comment by bsvobodny** [comment]
I just add a topic on the Sonar Community website, I hope that I will have more chance there to reach someone : https://community.sonarsource.com/t/action-leaves-scannerwork-folder-owned-by-root-in-case-of-cancel-during-the-step/67330

**Comment by wouter-admiraal-sonarsource** [comment]
Hi everyone. Sorry for the late reply. Thanks for the report, and thanks @bsvobodny for [your PR](https://github.com/SonarSource/sonarqube-scan-action/pull/33). I've added a comment, feel free to reach out if you need any help addressing it.

I've also created a ticket on our side to track this: https://jira.sonarsource.com/browse/SQSCANGHA-3

I will now close this thread.

**Comment by wouter-admiraal-sonarsource** [comment]
Yes, it's supposed to be fixed on 1.2.0 (released in December)
