### ISSUE TITLE
It is not capturing the code coverage in PR 

### ISSUE THREAD

**Issue by karthik-philips-ta** [SonarSource/sonarqube-scan-action#32]
When I ran the sonarqube scan action and provided the coverage file for the python script, The sonar scan executes without error but in the portal there it shows coverage as 0.0

**Comment by wouter-admiraal-sonarsource** [comment]
Hi,

FYI, your issue isn't specifically tied to the GitHub Action, but rather to how analysis is configured. You may have more luck reaching out to the [wider community](https://community.sonarsource.com/) for such questions.

How are you computing your code coverage for python, and how are you passing this info to the scanner? Have you checked [the documentation](https://docs.sonarqube.org/latest/analysis/test-coverage/python-test-coverage/), and correctly configured `sonar.python.coverage.reportPaths` (see [Usage](https://github.com/SonarSource/sonarqube-scan-action#usage))?

**Comment by wouter-admiraal-sonarsource** [comment]
I'm closing this issue now, for lack of traction. Feel free to contact the community if you need more help.

**Comment by timdittler** [comment]
It's a bit weird to configure for python, so I'm pointing to a helpful [StackOverflow thread](https://stackoverflow.com/a/78087226/2095866).
