### ISSUE TITLE
Error with github actions sonarsource/sonarqube-scan-action@v1.0.0

### ISSUE THREAD

**Issue by anuragkusingh-kr** [SonarSource/sonarqube-scan-action#40]
Build container for action use: '/runner/_work/_actions/sonarsource/sonarqube-scan-action/v1.0.0/Dockerfile'.
 check_suite_focus=true#step:4:5)1fd20c25c -f "/runner/_work/_actions/sonarsource/sonarqube-scan-action/v1.0.0/Dockerfile" "/runner/_work/_actions/sonarsource/sonarqube-scan-action/v1.0.0"
  Sending build context to Docker daemon  44.03kB
  
  Step 1/7 : FROM sonarsource/sonar-scanner-cli:4.[6
  Head "https://registry-1.docker.io/v2/sonarsource/sonar-scanner-cli/manifests/4.6": received unexpected HTTP status: 500 Server Error
  Warning: Docker build failed with exit code 1, back off 9.819 seconds before retry.
  /usr/local/bin/docker build -t 60e226:d38a33c23f[7]c -f "/runner/_work/_actions/sonarsource/sonarqube-scan-action/v1.0.0/Dockerfile" "/runner/_work/_actions/sonarsource/sonarqube-scan-action/v1.0.0"
  Sending build context to Docker daemon  44.03kB
  
  Step 1/7 : FROM sonarsource/sonar-scanner-cli:4.6
  unauthorized: authentication required
  Warning: Docker build failed with exit code 1, back off 5.5 seconds before retry.
  /usr/local/bin/docker build -t 60e226:d38a33c23f70442cb7022e51fd20c25c -f "/runner/_work/_actions/sonarsource/sonarqube-scan-action/v1.0.0/Dockerfile" "/runner/_work/_actions/sonarsource/sonarqube-scan-action/v1.0.0"
  Sending build context to Docker daemon  44.03kB
  
  Step 1/7 : FROM sonarsource/sonar-scanner-cli:4.6
  received unexpected HTTP status: 500 Server Error
Error: Docker build failed with exit code 1

**Comment by henryju** [comment]
We are not actively monitoring GitHub issues. For feedback or feature requests on this action, please go to our [Community forum](https://community.sonarsource.com/c/sq/10).
