### ISSUE TITLE
sonar-scanner: command not found

### ISSUE THREAD

**Issue by molinx** [SonarSource/sonarqube-scan-action#45]
We are getting this error when running the action:

```sh
/entrypoint.sh: line 35: sonar-scanner: command not found
  ❌  Failure - Main SonarQube scan
exit with `FAILURE`: 127
```

We were able to fix it by changing this line:
https://github.com/SonarSource/sonarqube-scan-action/blob/50d5d981633b1b78cd3bc540ec4a7e18bb295ee5/entrypoint.sh#L35

to an absolute path: 
`/opt/sonar-scanner/bin/sonar-scanner -Dsonar.projectBaseDir=${INPUT_PROJECTBASEDIR} ${INPUT_ARGS}`

Is this something that can be added? Or it should be fixed in another way (or our end)?

**Comment by raphaelperrin24** [comment]
Hi, I had the same issue on on-prem runner which already had sonar-scanner installed to a different path.

Removing it from the runner fixed the issue.

**Comment by henryju** [comment]
We are not actively monitoring GitHub issues. For feedback or feature requests on this action, please go to our [Community forum](https://community.sonarsource.com/c/sq/10).
