### ISSUE TITLE
Scanning for Java and Gradle Skipped

### ISSUE THREAD

**Issue by nkreiger** [SonarSource/sonarqube-scan-action#51]
Is there a reason this isn't optional, and it will always skip if the `pom.xml` and `build.gradle` files exist in the scanning dir?

I have a strong case for an enterprise pipeline where we are working on standardizing our CI system so that everything runs through the same sonarqube action. If java and maven are treated differently, we are unable to inject the appropriate properties that are essential for our downstream reporting.

Adding a simple input flag that allows you to still run the scan would be quite easy, is there pushback against that?

**Comment by josearaujo** [comment]
any updates?

**Comment by henryju** [comment]
Hi, we are going to change the action to not fail in the presence of a Maven/Gradle project. Instead, we simply log a message to inform you that this is not our recommendation.
Here is the ticket: https://sonarsource.atlassian.net/browse/SQSCANGHA-26
