### ISSUE TITLE
Use `sonar-project.properties` to provide `SONAR_HOST_URL`

### ISSUE THREAD

**Issue by lukasz-mitka** [SonarSource/sonarqube-scan-action#53]
Since `SONAR_HOST_URL` is a **Required** input I have to duplicate the value in both `sonar-project.properties` and GHA workflow.

**Comment by henryju** [comment]
@agigleux what do you think of this request?

**Comment by henryju** [comment]
@agigleux for some reason, the GitHub action makes it a requirement to set `SONAR_HOST_URL`. I agree this is not compliant with our other scanners, so I would be in favor of dropping this.

**Comment by lukasz-mitka** [comment]
@henryju thanks, would be great to make it optional input.

**Comment by henryju** [comment]
Ticket created: https://sonarsource.atlassian.net/browse/SQSCANGHA-31

**Comment by lukasz-mitka** [comment]
Fixed in #125.
Thanks @henryju!
