### ISSUE TITLE
Feature request: ARM64 Images

### ISSUE THREAD

**Issue by PatrickMennen** [SonarSource/sonarqube-scan-action#54]
As described already in the title. We are currently experimenting with ARM64-based builds and have gained a significant increase in CI-pipeline speed. Unfortunately the Sonarqube scan action has no ARM docker image available on docker-hub. 

Would it be possible to publish the docker image for the scanner for this architecture?

**Comment by henryju** [comment]
Hi, We plan to better support ARM64, not only in this action but for all our scanners. This is likely to happen later this year.

Please follow this ticket: https://sonarsource.atlassian.net/browse/SQSCANGHA-32
