### ISSUE TITLE
[Question] - How to use ansible-lint with github actions ?

### ISSUE THREAD

**Issue by Merrick28** [SonarSource/sonarqube-scan-action#55]
All is in the title... :)

I have a project with ansible files, and I'd like to check them. I managed to do it using on my  laptop using a custom docker image, but I'd like to do it using github actions.
When I use the "standard" way, I have : 
```
ERROR: Error executing command: Cannot run program "ansible" (in directory "/github/workspace"): error=2, No such file or directory
WARN: Cannot get ansible version
ERROR: Error executing command: Cannot run program "ansible-lint" (in directory "/github/workspace"): error=2, No such file or directory
WARN: Cannot get ansible-lint version
ERROR: Error executing command: Cannot run program "ansible-lint" (in directory "/github/workspace"): error=2, No such file or directory
```

Is there a way to add ansible support on the image ?

Thanks in advance.

**Comment by henryju** [comment]
Hi, sorry for the late answer, but I fail to see how it relates to SonarQube. Please open a thread in our [community forum](https://community.sonarsource.com/) if you still need help on this topic.
