### ISSUE TITLE
Add GitHub Advanced Security Code Scanning integration

### ISSUE THREAD

**Issue by aegilops** [SonarSource/sonarqube-scan-action#57]
I'm looking for a way to integrate SonarQube into GitHub Advanced Security running on GitHub Enterprise Server.

I know this Action exists for use with GitHub Enterprise, to integrate with Pull Requests.

What I'd like is a way to get SARIF out of SonarQube into the GitHub Advanced Security Code Scanning interface using the [`upload-sarif` Action](https://github.com/github/codeql-action/tree/main/upload-sarif).

**Comment by antoine-vinot-sonarsource** [comment]
Hi there,

Sorry for the (very) late answer. We are not very active on these issues and usually encourage people to post on [our forum](https://community.sonarsource.com/) directly.

We support the push of Vulnerabilities from SonarQube to GitHub Advanced Security Code Scanning (check [the documentation here](https://docs.sonarsource.com/sonarqube/latest/devops-platform-integration/github-integration/setting-up-integration/#github-code-scanning-alerts-for-security-vulnerabilities)). This is only available starting in the Developer edition though.

However, I don't think what you are looking for is possible as we don't support SARIF export at the moment (only import).
