### ISSUE TITLE
failing with self hosted runner

### ISSUE THREAD

**Issue by prosper-sre** [SonarSource/sonarqube-scan-action#59]
#7 [3/3] RUN chmod +x /entrypoint.sh
  #7 sha256:dff1aa098100636ae4018b72a22136284c1f41087dbeaf2e45ec833a93a641f6
  #7 0.285 chmod: /entrypoint.sh: Operation not permitted
  #7 ERROR: process "/bin/sh -c chmod +x /entrypoint.sh" did not complete successfully: exit code: 1
  ------
   > [3/3] RUN chmod +x /entrypoint.sh:
  ------
  process "/bin/sh -c chmod +x /entrypoint.sh" did not complete successfully: exit code: 1
Error: Docker build failed with exit code 1

**Comment by ffineis** [comment]
+1

**Comment by henryju** [comment]
I am closing this issue as outdated. If you still encounter the problem, please open a thread in our [community forum](https://community.sonarsource.com/).
