### ISSUE TITLE
Update docs to explain fetch-depth: 0 recommendation

### ISSUE THREAD

**Issue by jeremy-daley-kr** [SonarSource/sonarqube-scan-action#62]
Please see:
https://github.com/SonarSource/sonarqube-scan-action/blob/master/README.md?plain=1#L48

It's a pretty hefty recommendation to suggest `fetch-depth: 0`, as it substantially increases Github workflow run times.

It'd be nice to have it in the README file, but can someone at least mention here what is to be gained by fetching the full git history?

Thanks!

**Comment by henryju** [comment]
Hi,

Sorry for the late answer. You can find some information on this page: https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/scm-integration/
Basically, SonarQube needs the full repo history for some features:
* issue auto-assignement (based on the SCM author)
* issues dating/clean as you code (we need to find when the issue has been introduced)
