### ISSUE TITLE
Feature Request - Support security hardening with OpenID Connect

### ISSUE THREAD

**Issue by Smirl** [SonarSource/sonarqube-scan-action#63]
# Summary

The action currently requires `SONAR_TOKEN` environment variable to be set. This requires an out of band process to keep this refreshed with short lived token, or keeping credentials that never expire which is dangerous.

For organisations with many repositories this requires either organisation level secret, or many repository level secrets.

Github Actions now supports (and recommends?) using the IdP token available from actions (via `core.getIDToken()` or otherwise) to exchange for a short lived access token.

Would this be something that could be supported by Sonarqube, and then this action?

## Links

- [About security hardening with OpenID Connect](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect)
- [Configuring OpenID Connect in cloud providers](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers)
- [aws action example](https://github.com/aws-actions/configure-aws-credentials)

**Comment by antoine-vinot-sonarsource** [comment]
@agigleux I don't think this is something we have on our radar, do we?

**Comment by antoine-vinot-sonarsource** [comment]
I have brought this Feature Request to PMs through our internal tool.
