### ISSUE TITLE
SONAR_ROOT_CERT : keytool error: java.io.FileNotFoundException

### ISSUE THREAD

**Issue by alexandre-girard-maif** [SonarSource/sonarqube-scan-action#69]
Hi, since today, without any modification in our workflow, we've got an error: 

![image](https://user-images.githubusercontent.com/77633105/233934922-2b7e60cc-c1e1-47f3-80fe-bd0128435396.png)

and i see that today the image sonarsource/sonar-scanner-cli as change, maybe there is a regression

there is nothing special in our workflow 

`            - name: SonarQube Scan
              uses: sonarsource/sonarqube-scan-action@master
              with:
                  args: >
                      -Dsonar.sources=src,configuration,assets
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_IO_TOKEN }}
                  SONAR_HOST_URL: ${{ secrets.SONAR_IO_HOST_URL }}
                  SONAR_ROOT_CERT: ${{ secrets.SONAR_IO_ROOT_CERT }}`

**Comment by csaba-feher-sonarsource** [comment]
Hi @alexandre-girard-maif,

ItI'm sorry for the inconvenience, it was a release failure, we are not maintaining the issues fields so future questions please open on https://community.sonarsource.com/categories.

Thanks 
Csaba
