### ISSUE TITLE
ARM64 ubuntu self hosted runner breaks at startup 

### ISSUE THREAD

**Issue by Joeri-Abbo** [SonarSource/sonarqube-scan-action#73]
We are migrating from X64 to ARM64 processor architectur and that includes the runners. When I tried using the workflow below it breaks is ARM64 not supported or did I implement something bad? 

'''name: SonarQube
    
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Sonarqube
    runs-on: [ ARM64 ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}\n
'''
# Log below

Build container for action use: '/home/runner/actions-runner-21/_work/_actions/sonarsource/sonarqube-scan-action/master/Dockerfile'.
  /usr/bin/docker build -t eda936:7c8a83eeed3744d681fa359b1110d116 -f "/home/runner/actions-runner-[2](https://github.com/tracefy/aws-ec2-mcrn001/actions/runs/5081227533/jobs/9129275953#step:2:2)1/_work/_actions/sonarsource/sonarqube-scan-action/master/Dockerfile" "/home/runner/actions-runner-21/_work/_actions/sonarsource/sonarqube-scan-action/master"
  #1 [internal] load build definition from Dockerfile
  #1 transferring dockerfile: 711B done
  #1 DONE 0.0s
  
  #2 [internal] load .dockerignore
  #2 transferring context: 2B done
  #2 DONE 0.0s
  
  #3 [internal] load metadata for docker.io/sonarsource/sonar-scanner-cli:4.8
  #3 DONE 0.2s
  
  #4 [1/5] FROM docker.io/sonarsource/sonar-scanner-cli:4.8@sha256:24eb68efdb3ff2674a630e7b4387a10c8fc412c2438fbfa9188cd3e3a5a04c1d
  #4 DONE 0.0s
  
  #5 [internal] load build context
  #5 transferring context: 65B 0.0s done
  #5 DONE 0.0s
  
  #6 [2/5] COPY entrypoint.sh /entrypoint.sh
  #6 CACHED
  
  #7 [3/5] RUN chmod +x /entrypoint.sh
  #7 0.529 exec /bin/sh: exec format error
  #7 ERROR: process "/bin/sh -c chmod +x /entrypoint.sh" did not complete successfully: exit code: 1
  ------
   > [3/5] RUN chmod +x /entrypoint.sh:
  #7 0.529 exec /bin/sh: exec format error
  ------
  Dockerfile:14
  --------------------
    12 |     
    13 |     COPY entrypoint.sh /entrypoint.sh
    14 | >>> RUN chmod +x /entrypoint.sh
    15 |     COPY cleanup.sh /cleanup.sh
    16 |     RUN chmod +x /cleanup.sh
  --------------------
  ERROR: failed to solve: process "/bin/sh -c chmod +x /entrypoint.sh" did not complete successfully: exit code: 1
  Warning: Docker build failed with exit code 1, back off 9.562 seconds before retry.
  /usr/bin/docker build -t eda936:7c8a83eeed3744d681fa359b1110d116 -f "/home/runner/actions-runner-21/_work/_actions/sonarsource/sonarqube-scan-action/master/Dockerfile" "/home/runner/actions-runner-21/_work/_actions/sonarsource/sonarqube-scan-action/master"
  #1 [internal] load .dockerignore
  #1 transferring context: 2B done
  #1 DONE 0.0s
  
  #2 [internal] load build definition from Dockerfile
  #2 transferring dockerfile: 711B done
  #2 DONE 0.0s
  
  #[3](https://github.com/tracefy/aws-ec2-mcrn001/actions/runs/5081227533/jobs/9129275953#step:2:3) [internal] load metadata for docker.io/sonarsource/sonar-scanner-cli:[4](https://github.com/tracefy/aws-ec2-mcrn001/actions/runs/5081227533/jobs/9129275953#step:2:4).8
  #3 DONE 0.4s
  
  #4 [1/[5](https://github.com/tracefy/aws-ec2-mcrn001/actions/runs/5081227533/jobs/9129275953#step:2:5)] FROM docker.io/sonarsource/sonar-scanner-cli:4.8@sha25[6](https://github.com/tracefy/aws-ec2-mcrn001/actions/runs/5081227533/jobs/9129275953#step:2:6):24eb68efdb3ff26[7](https://github.com/tracefy/aws-ec2-mcrn001/actions/runs/5081227533/jobs/9129275953#step:2:7)4a630e7b43[8](https://github.com/tracefy/aws-ec2-mcrn001/actions/runs/5081227533/jobs/9129275953#step:2:8)7a10c8fc412c2438fbfa[9](https://github.com/tracefy/aws-ec2-mcrn001/actions/runs/5081227533/jobs/9129275953#step:2:9)188cd3e3a5a04c1d
  #4 DONE 0.0s
  
  #5 [internal] load build context
  #5 transferring context: 65B done
  #5 DONE 0.0s
  
  #6 [2/5] COPY entrypoint.sh /entrypoint.sh
  #6 CACHED
  
  #7 [3/5] RUN chmod +x /entrypoint.sh
  #7 0.655 exec /bin/sh: exec format error
  #7 ERROR: process "/bin/sh -c chmod +x /entrypoint.sh" did not complete successfully: exit code: 1
  ------
   > [3/5] RUN chmod +x /entrypoint.sh:
  #7 0.655 exec /bin/sh: exec format error
  ------
  Dockerfile:14
  --------------------
    12 |     
    13 |     COPY entrypoint.sh /entrypoint.sh
    14 | >>> RUN chmod +x /entrypoint.sh
    15 |     COPY cleanup.sh /cleanup.sh
    16 |     RUN chmod +x /cleanup.sh
  --------------------
  ERROR: failed to solve: process "/bin/sh -c chmod +x /entrypoint.sh" did not complete successfully: exit code: 1
  Warning: Docker build failed with exit code 1, back off 5.404 seconds before retry.
  /usr/bin/docker build -t eda936:7c8a83eeed3744d681fa359b11[10](https://github.com/tracefy/aws-ec2-mcrn001/actions/runs/5081227533/jobs/9129275953#step:2:10)d[11](https://github.com/tracefy/aws-ec2-mcrn001/actions/runs/5081227533/jobs/9129275953#step:2:11)6 -f "/home/runner/actions-runner-21/_work/_actions/sonarsource/sonarqube-scan-action/master/Dockerfile" "/home/runner/actions-runner-21/_work/_actions/sonarsource/sonarqube-scan-action/master"
  #1 [internal] load .dockerignore
  #1 transferring context:
  #1 transferring context: 2B 0.0s done
  #1 DONE 0.1s
  
  #2 [internal] load build definition from Dockerfile
  #2 transferring dockerfile: 711B 0.1s done
  #2 DONE 0.1s
  
  #3 [internal] load metadata for docker.io/sonarsource/sonar-scanner-cli:4.8
  #3 DONE 0.4s
  
  #4 [1/5] FROM docker.io/sonarsource/sonar-scanner-cli:4.8@sha256:24eb68efdb3ff2674a630e7b4387a10c8fc4[12](https://github.com/tracefy/aws-ec2-mcrn001/actions/runs/5081227533/jobs/9129275953#step:2:12)c2438fbfa9188cd3e3a5a04c1d
  #4 DONE 0.0s
  
  #5 [internal] load build context
  #5 transferring context: 65B 0.0s done
  #5 DONE 0.0s
  
  #6 [2/5] COPY entrypoint.sh /entrypoint.sh
  #6 CACHED
  
  #7 [3/5] RUN chmod +x /entrypoint.sh
  #7 0.980 exec /bin/sh: exec format error
  #7 ERROR: process "/bin/sh -c chmod +x /entrypoint.sh" did not complete successfully: exit code: 1
  ------
   > [3/5] RUN chmod +x /entrypoint.sh:
  #7 0.980 exec /bin/sh: exec format error
  ------
  Dockerfile:14
  --------------------
    12 |     
    [13](https://github.com/tracefy/aws-ec2-mcrn001/actions/runs/5081227533/jobs/9129275953#step:2:13) |     COPY entrypoint.sh /entrypoint.sh
    [14](https://github.com/tracefy/aws-ec2-mcrn001/actions/runs/5081227533/jobs/9129275953#step:2:14) | >>> RUN chmod +x /entrypoint.sh
    [15](https://github.com/tracefy/aws-ec2-mcrn001/actions/runs/5081227533/jobs/9129275953#step:2:15) |     COPY cleanup.sh /cleanup.sh
    [16](https://github.com/tracefy/aws-ec2-mcrn001/actions/runs/5081227533/jobs/9129275953#step:2:16) |     RUN chmod +x /cleanup.sh
  --------------------
  ERROR: failed to solve: process "/bin/sh -c chmod +x /entrypoint.sh" did not complete successfully: exit code: 1
Error: Docker build failed with exit code 1

**Comment by dbuades** [comment]
Same problem here

**Comment by jCOTINEAU** [comment]
Hello everyone, the sonar-scanner-cli docker image is not compatible nor built for ARM64 yet.

The topic is not yet scheduled, stay tuned for more information.

**Comment by henryju** [comment]
Hi folks, I have create a ticket to track this task, since we are about to close GitHub issues on this repo:
https://sonarsource.atlassian.net/browse/SQSCANGHA-32
