### ISSUE TITLE
Unable to resolve action `sonarsource/sonarqube-scan-action@master`, repository not found on this server. 

### ISSUE THREAD

**Issue by themahesh56** [SonarSource/sonarqube-scan-action#76]
Hi,
While trying to integrate Sonarqube with Github actions implementing below piece of code in GithubActions workflow.

- name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

But, getting below error - 

**Unable to resolve action `sonarsource/sonarqube-scan-action@master`, repository not found on this server.** 

Kindly help us on this .

**Comment by haully** [comment]
Hi, I'm using the snippet provided by the marketplace, works for me:
```
              - name: Official SonarQube Scan
                uses: SonarSource/sonarqube-scan-action@v2.0.1
            
```
[Official SonarQube Scan](https://github.com/marketplace/actions/official-sonarqube-scan)

![image](https://github.com/SonarSource/sonarqube-scan-action/assets/19169297/77be282c-a4fe-4eaa-b479-1d3dfa7ba650)

**Comment by antoine-vinot-sonarsource** [comment]
I don't understand what could have happened here. The error message indicates that the repository ID is wrong, but it looks good 🤷‍♂️
I'm closing the issue since it is 10 months old. If this issue is still valid, feel free to reach out on [our community forum](https://community.sonarsource.com/).
