### ISSUE TITLE
Github localhost server cannot be reached

### ISSUE THREAD

**Issue by FloAlbaux** [SonarSource/sonarqube-scan-action#84]
I have a SonarQube instance self-hosted on localhost:9000. I have followed the steps given by SonarQube itself, including setting two secret variables (secrets.SONAR_TOKEN and secrets.SONAR_HOST_URL=http://127.0.0.1:9000/ in my case). I have also created a sonar-project.properties file with my sonar.projectKey, and I have created a new file named ".github/workflows/build.yml."

`name: Build

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}`
      
And I still encounter the same error when launching the pipeline:

ERROR: SonarQube server [http://localhost:9000] cannot be reached.

When I run this command locally, it works fine:

`docker run --network=host -e SONAR_HOST_URL='http://127.0.0.1:9000' \
        --user="$(id -u):$(id -g)" -v "$PWD:/usr/src" sonarsource/sonar-scanner-cli`
       
 Can someone please help me? Thank you very much.
 
 
 If it can be relevente her my docker-compose 
 `version: '3'

services:
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    depends_on:
      - sonarqube-db

  sonarqube-db:
    image: postgres:12
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - sonarqube_db:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonarqube_db:
`

**Comment by sheikhasim** [comment]
+1

**Comment by FranParraguez** [comment]
alguien tiene alguna solucion?

**Comment by larsverp** [comment]
As mentioned on the readme:

> To run an analysis on your code, you first need to set up your project on SonarQube. Y**our SonarQube instance must be accessible from GitHub**, and you will need an access token to run the analysis (more information below under Environment variables).

**Comment by antoine-vinot-sonarsource** [comment]
As @larsverp mentioned above, the SonarQube instance must be accessible from Github, which is not the case with localhost.
