### ISSUE TITLE
ERROR: SonarQube server [http://sonar-sonarqube.sonar.svc.cluster.local] can not be reached

### ISSUE THREAD

**Issue by namhyuck-kim-otsk** [SonarSource/sonarqube-scan-action#87]
Hello,

I am getting the following error while running the GitHub Workflow:

`ERROR: SonarQube server [http://sonar-sonarqube.sonar.svc.cluster.local/] can not be reached`

I am using self-hosted runner on running on private kubernetes cluster and sonarqube is setup on the same cluster but on different namespace. Thus, I am using the service address (<service-name>.<namespace>.svc.cluster.local) for the SONAR_URL variable.

`curl` command on the gh-runner to the address above works fine.

**Comment by Keshapally** [comment]
what was the solution ?
