### ISSUE TITLE
Update Java version in sonarqube-scan-action

### ISSUE THREAD

**Issue by NielsCalis** [SonarSource/sonarqube-scan-action#88]
Currently when running the main version of sonarqube-scan-action, I receive the following error in SonarQube dashabord wanings:
"SonarScanner will require Java 17 to run, starting in SonarQube 10.3. Please upgrade the version of Java that executes the scanner and refer to [the documentation](https://docs.sonarsource.com/sonarqube/10.2/analyzing-source-code/scanner-environment/) if needed."

Here, we currently still use SQ 10.2 but this will probably soon be upgraded to 10.3.

**Comment by csaba-feher-sonarsource** [comment]
Hi @NielsCalis, The Scanner CLI is already running on Java 17.
