### ISSUE TITLE
[Question] how the source code is checked out into the scanner cli container?

### ISSUE THREAD

**Issue by xyziven** [SonarSource/sonarqube-scan-action#92]
The source code is checked out by runner, and I think the code is located on OS filesystem of the runner. But the sonar scanner CLI works in container. How the source code is accessed by the scanner CLI? 
I'm doing the similar in self hosted Gitea and Gitea runner. (Gitea Actions is compatible with GHA)
I'm able to check out the source code by checkout action and the sonar scanner CLI is up. However, nothing was scanned. It indicated 0 source files. 
| 10:19:29.968 INFO: 0 source files to be analyzed
| 10:19:30.078 INFO: 0/0 source files have been analyzed

I think the reason is that the source code is checked out to the runner OS, while the scanner CLI is in container.  Am I right?
Thank you!

**Comment by csaba-feher-sonarsource** [comment]
Hi @xyziven,

Did your issue get resolved? Yes, the code is checked out on the runner OS, and the Scanner CLI is running in the container, accessing the file's location as input.
Future questions we try to answer on the https://community.sonarsource.com
