### ISSUE TITLE
Action leaves .scannerwork in _work folder under root privilages

### ISSUE THREAD

**Issue by vilup** [SonarSource/sonarqube-scan-action#94]
Hi all basically what the title says I have a problem where sonarqube leaves all files in the .scannerwork folder under root privilages. 
<img width="699" alt="Screenshot 2024-01-31 at 16 22 10" src="https://github.com/SonarSource/sonarqube-scan-action/assets/47676039/b53171e2-50c0-4a34-9f80-10340bf3c7f0">
And because I am cleaning up the runner on every run of that workflow it is failing on permission denied when deleting this folder

![Screenshot 2024-01-31 at 16 25 20](https://github.com/SonarSource/sonarqube-scan-action/assets/47676039/ee33950d-f181-4bc5-8db2-eaf8e168125a)

**Comment by michael-vonkeitz** [comment]
I have the same issue. But it only happens, if the sonarqube-scan-action is cancelled before it´s finished.
When it finished normally, it seems to clean up the folder itself.

**Comment by JAGonzaleDiaz** [comment]
the issue is being fixed here https://github.com/SonarSource/sonarcloud-github-action/releases/tag/v2.1.0 i guess same solution should be applied to this one. I have this issue using Xray scan after sonarqube with this action.

**Comment by istvan-bodo-sonarsource** [comment]
Thank you for your feedback, a ticket has been created for this: https://sonarsource.atlassian.net/browse/SQSCANGHA-29
